notes/urls.py
from django.urls import path

import notes.views

app_name = 'notes'

urlpatterns = [
    path('', notes.views.workspace, name='workspace'),
]

otm/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from notes.views import workspace_redirect

from notes.views import NotesAPIView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', workspace_redirect, name='workspace_redirect'),
    path('notes/', include('notes.urls', namespace='notes')),
    path('users/', include('users.urls', namespace='users')),

    path('api/v1/noteslist/', NotesAPIView.as_view()),
    path('api/v1/noteslist/<int:pk>/', NotesAPIView.as_view()),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import logout

import users.views

app_name = 'users'

urlpatterns = [
    path('login/', users.views.login, name='login'),
    path('register/', users.views.register, name='register'),
    path('profile/', users.views.profile, name='profile'),
    path('logout/', logout, name='logout'),
]

notes/models.py
from users.models import User
from django.db import models

# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=17)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=False)
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
     image = models.ImageField(upload_to='user_images', null=True, blank=True)
     notes_quanity = models.IntegerField(default=0)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms

from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'text-input',
            'placeholder': "input user name",
            'maxlength': "16",
        }))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': "text-input",
            'placeholder': "input password",
            'maxlength': "16",
        }))

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'text-input',
            'placeholder': "input user name",
            'maxlength': "16",
        }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'text-input',
        'placeholder': "input e-mail",
        'maxlength': "56",
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': "text-input",
            'placeholder': "input password",
            'maxlength': "16",
            'type': 'password',
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': "text-input",
            'placeholder': "repeat password",
            'maxlength': "16",
            'type': 'password',
        }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'text-input',
            'maxlength': "16",
        }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'text-input',
        'maxlength': "56",
        'readonly': True,
    }))
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'image')

notes/views.py
from django.shortcuts import render, redirect

from .serializers import NoteSerializer

from rest_framework.response import Response
from rest_framework.views import APIView

from notes.models import Note
from users.models import User


def workspace(request):
    return render(request, 'notes/workspace.html')

def workspace_redirect(request):
    return redirect('notes/')

class NotesAPIView(APIView):
    def get(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        if not pk:
            return Response({"error": "Method PUT not allowed"})
        lst = Note.objects.filter(user=User(id=pk)).values()
        #serializer = NoteSerializer(lst, many=True)
        if lst:
            return Response(lst)
        return Response({"error": "Objects does not exist"})

    def post(self, request):
        serializer = NoteSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        note_new = Note.objects.create(
            title=request.data['title'],
            description=request.data['description'],
            created_at=request.data['created_at'],
            completed=request.data['completed'],
            user=User(id=request.data['user_id'])
        )
        return Response({'note': NoteSerializer(note_new).data})

    def put(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        if not pk:
            return Response({"error": "Method PUT not allowed"})
        try:
            instance = Note.objects.get(id=pk)
        except Exception as exp:
            return Response({"error": str(exp)})

        serializer = NoteSerializer(data=request.data, instance=instance)
        serializer.user = User(id=request.data['user_id'])
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response({"note": serializer.data})

    def delete(self, request, *args, **kwargs):
        pk = kwargs.get("pk", None)
        if not pk:
            return Response({"error": "Method DELETE not allowed"})

        try:
            obj_del = Note.objects.get(pk=pk)
            obj_del.delete()
        except Exception as exp:
            return Response({"error": str(exp)})
            #return Response({"error": "Object does not exist"})

        return Response({"note": f'note {pk} deleted'})

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib import auth, messages

from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('workspace_redirect'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)

def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notes:workspace'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

notes/templates/notes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="rus">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %} {% endblock %}
    <!-- timer -->
    <script src="/static/front/js/timer.js" defer></script>
    <!--navbar-menu-->
    <script src="/static/front/js/navbar-menu.js" defer></script>
    <!-- table -->
    <script src="/static/front/js/app.js" defer></script>
    <!-- sort-->
    <script src="/static/front/js/sort.js" defer></script>

    {% block modal-css %} {% endblock %}

</head>
<body>
    <nav class="navbar">
    <div class="conteiner">
        <a href="{% url 'notes:workspace' %}"><img class="calendar-icon" src="/static/front/img/calendar-icon.png"></a>

        <div class="timer">
            <H2 class="timer-date" id="timer-date">01.01.2024 Monday</H2>
            <H1 class="timer-time" id="timer-time">12:00:00</H1>
        </div>

        <div class="navbar-user">
            <ul class="navbar-nav">
                <li class="navbar-item1">
                    <a class="user-a" href="{% if user.is_authenticated %}{% url 'users:profile' %}{% else %}{% url 'users:login' %}{% endif %}">
                        {% if user.is_authenticated %}
                            {{ user.username }}
                            <p style="display: none" id="userId">{{ user.id }}</p>
                        {% else %}
                            welcome, guest!
                        {% endif %}

                    </a>
                </li>
                <li class="navbar-item2">
                    <a href="{% if user.is_authenticated %}{% url 'users:profile' %}{% else %}{% url 'users:login' %}{% endif %}"><img class="user-icon" src="/static/front/img/user-icon.png"></a>
                </li>
                {% if user.is_authenticated %}
                <li class="navbar-item3">
                    <button class="nav-menu-btn" id="nav-menu-btn"></button>
                    <ul class="nav-menu-ul" id="nav-menu-ul">
                        <li class="menu-btn"><a href="{% url 'users:profile'  %}">profile</a></li>
                        {% if user.is_superuser or user.is_staff %}
                            <li class="menu-btn" style="border-bottom: solid 1px black;"><a href="{% url 'admin:index' %}">Admin panel</a></li>
                        {% endif %}
                        <li class="menu-btn" style="border-radius: 0 0 5px 5px;"><a href="{% url 'users:logout' %}">log out</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}
    {% block css %} {% endblock %}
</body>
</html>

notes/templates/notes/workspace.html
{% extends 'notes/base.html' %}
{% load static %}

{% block title %}<title>workspace</title>{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/front/css/workspace.css">
{% endblock %}

{% block modal-css %}
    <link rel="stylesheet" href="/static/front/css/normalize.css">
    <link rel="stylesheet" href="/static/front/css/modal.css">
    <script defer src="/static/front/js/modal.js"></script>
{% endblock %}

{% block content %} 


<main>
{#    <section class="options-container">#}
{#        <p>...</p>#}
{#    </section>#}

    <div class="workspace">
        <nav class="table-nav">
            <ul class="sort-menu">
                <li>
                    <button class="workspace-button" 
                    id="sort">
                    sort by<img id="sort-pic" class="workspace-settings-icon"        src="/static/front/img/settings-icon.png"></button>
                    <ul class="sort-sub"  id="sort-window">
                        <li><button class="sort-btn" id="sort-name">name</button></li>
                        <li><button class="sort-btn" id="sort-date">date</button></li>
                        <li><button class="sort-btn" id="sort-size">size</button></li>
                    </ul>
                </li>

            </ul>
            <button class="workspace-button" id="open-modal-btn" style="margin-left: 16px;">
                create note <img class="pen-icon" src="/static/front/img/pen-icon.png">
            </button>
        </nav>
        <div class="workspace-table" id="table">
            
        </div>
    </div>
</main>

<div class="modal" id="my-modal1">
    <div class="modal__box">
        <button class="modal__close-btn" id="close-my-modal-btn">
            <svg width="23" height="25" viewBox="0 0 23 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M2.09082 0.03125L22.9999 22.0294L20.909 24.2292L-8.73579e-05 2.23106L2.09082 0.03125Z"
                    fill="#333333" />
                <path d="M0 22.0295L20.9091 0.0314368L23 2.23125L2.09091 24.2294L0 22.0295Z" fill="#333333" />
            </svg>
        </button>
        <h2>Create note</h2>

        <p><input class="input-note" type="text" placeholder="input note name"  maxlength="16" id="note-name"/></p>

        <p><input class="input-note" type="text" placeholder="input note description" maxlength="240" id="note-description"/></p>

        <button class="model-save-button" id="create-note-btn">save</button>
    </div>
</div>  
{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="rus">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <script src="/static/front/js/back.js" defer></script>
    <script src="/static/front/js/close.js" defer></script>
    {% block title %} {% endblock %}

</head>
<body>
   {% block content%} {% endblock %}
{% block css %} {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'front/css/login.css'%}">
{% endblock %}



{% block title %}
    <title>Login</title>
{% endblock %}

{% block content %}
     {% if messages or  form.non_field_errors %}
         <div class="{% if messages %}alert-success{% else %}alert-warning{% endif %}" id="alert">
        <strong></strong>
             {% if messages %}
                 {% for message in messages %}
                    {{ message }}
                 {% endfor %}
             {% else %}
                 {{ form.non_field_errors }}
             {% endif %}
        <button class="{% if messages %}close-success{% else %}close-warning{% endif %}" id="close"></button>
    </div>


     {% endif %}
	<div class="conteiner">
        <a href="#" class="back" id="link-back"></a>
        <header class="conteiner-header">
            <h3 class="header-text">Log in</h3>
        </header>

        <div class="conteiner-body">
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                <label for="{{ form.username.id_for_label }}">User name</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}">Password</label>
                {{ form.password }}
            </div>
            <div class="bottom-form-group">
                <a href="#" class="forgot-pass">Forgot password?</a>
                <input class="log-in-submit" type="submit" value="log in">
            </div>
            </form>
        </div>

        <div class="conteiner-footer">
            <a href="{% url 'users:register' %}" class="reg-a">Registration</a>
        </div>
   </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'notes/base.html' %}
{% load static %}

{% block title %} <title>Profile</title> {% endblock %}
{% block css %}
    <link rel="stylesheet" href="/static/front/css/profile.css"> 
    <link rel="stylesheet" href="/static/front/css/normalize.css">
{% endblock %}

{% block content %}
    <main>
    <h1>Profile</h1>
    <div class="pfp-div">
        <img class="pfp" src="{% if user.image %}
                            {{ user.image.url }}
                        {% else %}
                            {% static 'front/img/defaul-pfp.png' %}
                        {% endif %}">
    </div>
    <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="info">
        
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">User name</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}">e-mail adress</label>
                {{ form.email }}
            </div>
            
        </div>
        <div class="pic-input-div">
            {{ form.image }}
        </div>
        <div class="form-footer">
            <input class="save" type="submit" value="save">
        </div>
    </form>
    </main>
{% endblock %}

</body>
</html>

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'front/css/register.css' %}">
{% endblock %}

{% block title %}
	<title>Registration</title>
{% endblock %}

{% block content %}
    {% if form.errors %}
         <div class="alert" id="alert">
        <strong></strong>
             {{ form.errors }}
        <button class="close" id="close"></button>
    </div>
     {% endif %}
	<div class="conteiner">
        <a href="#" id="link-back" class="back"></a>
        <header class="conteiner-header">
            <h3 class="header-text">Create account</h3>
        </header>

        <div class="conteiner-body">
            <form action="{% url 'users:register' %}" method="post">
                {% csrf_token %}
            <div class="form-row">
                <div class="form-column">
                    <label for="{{ form.username.id_for_label }}">User name</label>
                    {{ form.username }}
                </div>
                <div class="form-column">
                    <label for="{{ form.email.id_for_label }}">e-mail</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-column">
                    <label for="{{ form.password1.id_for_label }}">password</label>
                    {{ form.password1 }}
                </div>
                <div class="form-column">
                    <label for="{{ form.password2.id_for_label }}">repeat password</label>
                    {{ form.password2 }}
                </div>
            </div>
            <div class="bottom-form-group">
                <input class="log-in-submit" type="submit" value="Create account">
            </div>
            </form>
        </div>

        <div class="conteiner-footer">
            <a href="{% url 'users:login' %}" class="reg-a">Autorisation</a>
        </div>
   </div>
{% endblock %}